#!/usr/bin/env bash

set -x

if [[ -d proj ]]; then
	cd proj
	BSP=`grep BSP: todo/todo-trunk.txt`
	BSPARR=($BSP)
	URL=${BSPARR[1]}
	source ../../.url_mapper
	NAME=`echo $URL | rev | cut -d/ -f1 | rev`
	TYPE=`echo $NAME | cut -d. -f1 | tr '[:upper:]' '[:lower:]'`

	cd ..
	git clone $URL
	ln -sf $NAME bsp
	cd bsp
	ln -sf $PRJ_ROOT/build-envs/just-$TYPE/justfile
fi
